language: python
cache: pip

python:
  - 3.6
  - 3.5
  - 3.4

script:
  python -m unittest discover tests --buffer

matrix:
  include:
    - python: 2.7
      install: pip install -r requirements.2.7.txt
